Added code tidy comments
stargate/data-api pull request #1311
Opened 2024-07-25 21:31 UTC by amorton

**What this PR does**:

Add comments for code that needs tidy up later. 

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [*] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [*] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

2024-07-26 19:24 UTC, tatu-at-datastax approved these changes

2024-07-30 15:36 UTC, jeffreyscarpenter commented
@amorton Can this feedback be converted into issues instead of merging more comments into the code?

2024-08-19 19:40 UTC, tatu-at-datastax approved these changes

2024-08-23 13:55 UTC, jeffreyscarpenter requested changes
let's not merge this, I will create separate tickets

2024-10-15 18:22 UTC, tatu-at-datastax commented
To be closed?

2024-10-23 15:10 UTC, jeffreyscarpenter commented
I have not had the time to go back and create tickets for these items @tatu-at-datastax

2026-06-11 15:26 UTC, tatu-at-datastax commented
Outdated, closing.

2026-06-11 15:26 UTC, closed without merging