[WIP] Refactor ErrorCode and JsonApiException
stargate/data-api pull request #1316
Opened 2024-07-29 15:47 UTC by Hazel-Datastax

**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

2024-08-13 23:29 UTC, amorton requested changes

2024-08-13 23:29 UTC, amorton commented on src/main/resources/errors.yaml
> +          Provider: $${provider}; HTTP Status: $${httpStatus}; Error Message: $${errorMessage}
it's because of the eclipse plugin, we will move to using Jackson

2024-08-13 23:29 UTC, amorton commented
Discussed with @Hazel-Datastax  I will pickup this and she is looking into how we start using the new error objects

2024-08-15 18:22 UTC, amorton approved these changes

2024-08-15 18:22 UTC, merged

2024-08-16 17:57 UTC, vkarpov15 reviewed
LGTM