tables insertMany ordered as true, faulty row in the middle should not fail the whole batch.
stargate/data-api pull request #1778
Opened 2024-12-04 23:47 UTC by Yuqi-Du

**What this PR does**:
When there is a faulty row in the entire batch of insertMany, and ordered as true.
Every row before the faulty row should succeed, and all the faulty row errors should propagate to the result.

**Which issue(s) this PR fixes**:
fixes: #1672

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

2024-12-13 14:54 UTC, jeffreyscarpenter commented
@Yuqi-Du what is the status of this PR?

2025-01-22 21:07 UTC, maheshrajamani commented on src/main/java/io/stargate/sgv2/jsonapi/service/operation/OperationAttemptContainer.java
> +      if (attempt == targetAttempt) {
The only place we use it is from ordered true, so do we need the loop? All we need to check is `targetAttempt.status() == OperationAttempt.OperationStatus.ERROR;`

2025-01-22 23:47 UTC, Yuqi-Du commented on src/main/java/io/stargate/sgv2/jsonapi/service/operation/OperationAttemptContainer.java
> +      if (attempt == targetAttempt) {
No, the loop is needed, this shouldFailFast() method is called for every row in the batch. 
Let's say rows are `a,b,c,d,e,f,g`.  When inserting row `d`, we need to know if any row before `d` is faulty, so these are `a,b,c` we need to check. If `c` is faulty, then inserting `d` will need to failfast.

2025-01-23 02:07 UTC, amorton requested changes

2025-01-23 02:07 UTC, amorton commented on src/main/java/io/stargate/sgv2/jsonapi/service/operation/OperationAttemptContainer.java
> +      if (attempt == targetAttempt) {
1) from maheshes comment, the purpose of targetAttempt is not clear. See above, write a @param doc comment. 
2) also need to make it clear, that this function will work for any attempt, not just the first one after the first failure. 
generally need a better explaination of what should be happening here, including what we expect to happen if say there are failures before we even start processing. e.g. the last attempt has a type error should we start the first ? 

I'm also wondering why we need targetAttempt (and I think we discussed this) can we fail if there are any failures in the group ?

2025-01-23 02:09 UTC, amorton requested changes
some thoughts to confirm the logic. 

the -1 is because this needs unit tests for the OperationAttemptContainer , we don't have any yet and it's just not possible to test this effectively using IT

2025-02-03 19:10 UTC, Yuqi-Du commented on src/main/java/io/stargate/sgv2/jsonapi/service/operation/OperationAttemptContainer.java
> +  public boolean shouldFailFast(AttemptT targetAttempt) {
added, thanks

2025-02-03 19:10 UTC, Yuqi-Du commented on src/main/java/io/stargate/sgv2/jsonapi/service/operation/OperationAttemptContainer.java
> +   *     at least one error before(include) the targetAttempt
changed, thanks

2025-02-03 21:52 UTC, vkarpov15 reviewed
LGTM

2025-09-29 20:03 UTC, closed without merging